publishDir = "./public"
baseURL = "http://localhost:9080"
languageCode = "en-us"
title = "FoodBankNear.Me"

relativeURLs = true

disableKinds = [ "taxonomy", "taxonomyTerm" ]
disableAliases = true
disableHugoGeneratorInject = true
enableRobotsTXT = true

[related]
includeNewer = true
toLower = false
threshold = 1.0
[[related.indices]]
  name = "state"
  weight = 1.0
[[related.indices]]
  name = "partnerGroupId"
  weight = 1.0

[params]
enableServiceWorker = false
disallowSearchEngines = true # set robots.txt to disallow everything
themeColor = "#2b5797"
safariPinnedTabColor = "#2b5797"
appName = "FoodBankNear.Me"
appShortName = "FBN.Me" # should be less than 12 characters
googleAnalyticsUA = ""
siteImage = "https://ucarecdn.com/4c74d42f-8949-41fc-abd4-2523d032ba34/-/format/auto/-/progressive/yes/-/scale_crop/1200x630/center/foodbanknearme"
siteDescription = "Find a food bank or pantry near you."
siteKeywords = "food, bank, pantry, near, close, free"
ogTitle = "FoodBankNear.Me"

# redirect any alternate hosts to the primary host
[params.host]
primary = "foodbanknear.me"
alternates = [
  "foodbanknearme-ef1a10.netlify.com"
]

# add redirects/headers
[outputs]
home = ["HTML", "REDIRECTS", "HEADERS", "WEBMANIFEST", "BROWSERCONFIG"]

page = ["html", "rss", "json"]
section = ["html", "rss", "json"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
delimiter = ""

[mediaTypes."application/vnd.geo+json"]
suffixes = ["geojson"]

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
notAlternative = true

[outputFormats.WEBMANIFEST]
baseName = "manifest.webmanifest"
isPlainText = true
notAlternative = true

[outputFormats.BROWSERCONFIG]
baseName = "browserconfig.xml"
isPlainText = true
notAlternative = true

[outputFormats.geojson]
isPlainText = true
mediaType = "application/vnd.geo+json"
