backend:
  name: bitbucket
  repo: fcnetlify/foodbanknear.me
  branch: admin-collections

media_folder: "static/uploads"
public_folder: "/uploads"
collections:

  - name: settings
    label: Settings
    label_singular: Setting
    delete: false
    editor:
      preview: false
    files:
      - name: primary
        label: "Primary Site Settings"
        file: _data/settings/primary.yml
        description: "Primary Site Settings"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Setting One", name: "setting_one", widget: "string" }
          - { label: "Setting Two", name: "setting_two", widget: "number" }
          - { label: "Setting Boolean", name: "setting_boolean", widget: "boolean", default: false }
      - name: secondary
        label: "Secondary Site Settings"
        file: _data/settings/secondary.json
        description: "Secondary Site Settings"
        fields:
          - { label: "Setting Three", name: "setting_three", widget: "string" }
          - { label: "Setting Four", name: "setting_four", widget: "number" }
          - { label: "Setting Five", name: "setting_five", widget: "boolean", default: false }

  - name: pages
    label: Pages
    label_singular: Page
    folder: content
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: faqs
    label: FAQs
    label_singular: FAQ
    folder: _faqs
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Slug", name: "title", widget: "string" }
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "text" }
      - { label: "Extended Answer", name: "body", widget: "markdown" }

  - name: locations
    label: Locations
    label_singular: Location
    folder: _locations
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Slug", name: "title", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - { label: "County", name: "county", widget: "string" }
      - label: State
        name: state
        widget: select
        options:
          - AA
          - AE
          - AK
          - AL
          - AP
          - AR
          - AS
          - AZ
          - CA
          - CO
          - CT
          - DC
          - DE
          - FL
          - GA
          - GU
          - HI
          - IA
          - ID
          - IL
          - IN
          - KS
          - KY
          - LA
          - MA
          - MD
          - ME
          - MI
          - MN
          - MO
          - MP
          - MS
          - MT
          - NC
          - ND
          - NE
          - NH
          - NJ
          - NM
          - NV
          - NY
          - OH
          - OK
          - OR
          - PA
          - PR
          - RI
          - SC
          - SD
          - TN
          - TX
          - UM
          - UT
          - VA
          - VI
          - VT
          - WA
          - WI
          - WV
          - WY
      - label: Website
        name: website
        widget: string
        pattern:
          - "https?://\\S+"
          - "http(s)://"
        hint: 'should begin with http:// or https://'
        required: false
      - label: Email
        name: email
        widget: string
        pattern:
          - "\\S+@\\S+"
          - "email@domain"
        required: false
      - label: Phone
        name: phone
        widget: string
        pattern:
          - "(\\d{3}-){2}\\d{4}"
          - "000-000-0000"
        required: false
      - label: Latitude
        name: latitude
        widget: number
        required: false
      - label: Longitude
        name: longitude
        widget: number
        required: false
      - { label: "Short Description", name: "description", widget: "string", required: false }
      - { label: "Extended Detail", name: "body", widget: "markdown", required: false }
