name: Update Data Feed

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2.4.1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: npm install
      run: |
        npm ci
        npm run updatedata

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: automated/datafeed
        commit-message: Update data feed
        title: Update data feed
        assignees: brandonaaron
