name: Update Data Feed

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.15.3
      uses: actions/setup-node@v1
      with:
        node-version: 10.15.3
    - name: npm install
      run: |
        npm ci
        npm run updatedata
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.2.2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch-suffix: none
        commit-message: Update data feed
        title: Update data feed
        assignees: brandonaaron
